// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "general_public_point_review": reservation Resource Client
//
// Command:
// $ goagen
// --design=github.com/work/general_public_point_review/design
// --out=$(GOPATH)/src/github.com/work/general_public_point_review
// --version=v1.3.0

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// EntryReservationPath computes a request path to the entry action of reservation.
func EntryReservationPath() string {

	return fmt.Sprintf("/general_public_point_review/reservation")
}

// EntryReservation makes a request to the entry action endpoint of the reservation resource
func (c *Client) EntryReservation(ctx context.Context, path string, payload *OccupyPayLoad) (*http.Response, error) {
	req, err := c.NewEntryReservationRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewEntryReservationRequest create the request corresponding to the entry action endpoint of the reservation resource.
func (c *Client) NewEntryReservationRequest(ctx context.Context, path string, payload *OccupyPayLoad) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	return req, nil
}
