// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "general_public_point_review": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/work/general_public_point_review/design
// --out=$(GOPATH)/src/github.com/work/general_public_point_review
// --version=v1.3.0

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// ReservationController is the controller interface for the Reservation actions.
type ReservationController interface {
	goa.Muxer
	Entry(*EntryReservationContext) error
}

// MountReservationController "mounts" a Reservation resource controller on the given service.
func MountReservationController(service *goa.Service, ctrl ReservationController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewEntryReservationContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*OccupyPayLoad)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Entry(rctx)
	}
	service.Mux.Handle("POST", "/general_public_point_review/reservation", ctrl.MuxHandler("entry", h, unmarshalEntryReservationPayload))
	service.LogInfo("mount", "ctrl", "Reservation", "action", "Entry", "route", "POST /general_public_point_review/reservation")
}

// unmarshalEntryReservationPayload unmarshals the request body into the context request data Payload field.
func unmarshalEntryReservationPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &occupyPayLoad{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
