// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "general_public_point_review": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/work/general_public_point_review/design
// --out=$(GOPATH)/src/github.com/work/general_public_point_review
// --version=v1.3.0

package app
